In [1]:
import pandas as pd

In [2]:
df_final = pd.read_csv('donnees_combinees.csv')
df = pd.read_csv('donnees_combinees.csv')
df.head()

,Entreprise,Nom_fichier,Type,Annee,Immobilisations incorporelles,Immobilisations corporelles,Produits loués,Participations comptabilisées,Autres investissements,Créances de financement des ventes,...,modele,unites_vendues,Résultats opérationnels,Marge brute,Résultat financier,Bénéfices avant impôt,Bénéfice net de l'année,vente,Continents,Pays
0,BMW,Actifs_BMW,Group,2021,12980.0,22390.0,44700.0,5112.0,1241.0,51712.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW,Actifs_BMW,Group,2020,12342.0,21850.0,41995.0,3585.0,735.0,48025.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMW,Actifs_BMW,Group,2019,11729.0,23245.0,42609.0,3199.0,703.0,51030.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BMW,Actifs_BMW,Group,2018,10971.0,19801.0,38572.0,2624.0,739.0,48109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW,Actifs_BMW,Group,2017,9464.0,18471.0,36257.0,2769.0,690.0,48321.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df['Type']= df['Type'].str.upper()
df = df[df['Type'] == 'GROUP']
df =df[df['Annee'].between(2016,2021)]
df

,Entreprise,Nom_fichier,Type,Annee,Immobilisations incorporelles,Immobilisations corporelles,Produits loués,Participations comptabilisées,Autres investissements,Créances de financement des ventes,...,modele,unites_vendues,Résultats opérationnels,Marge brute,Résultat financier,Bénéfices avant impôt,Bénéfice net de l'année,vente,Continents,Pays
0,BMW,Actifs_BMW,GROUP,2021,12980.0,22390.0,44700.0,5112.0,1241.0,51712.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW,Actifs_BMW,GROUP,2020,12342.0,21850.0,41995.0,3585.0,735.0,48025.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMW,Actifs_BMW,GROUP,2019,11729.0,23245.0,42609.0,3199.0,703.0,51030.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BMW,Actifs_BMW,GROUP,2018,10971.0,19801.0,38572.0,2624.0,739.0,48109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW,Actifs_BMW,GROUP,2017,9464.0,18471.0,36257.0,2769.0,690.0,48321.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,VW,Resultats_VW,GROUP,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9675.0,0.043408,1991.0,11667.0,8824.0,NaN,NaN,NaN
326,VW,Resultats_VW,GROUP,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16960.0,0.067133,1396.0,18356.0,14029.0,NaN,NaN,NaN
327,VW,Resultats_VW,GROUP,2018,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13920.0,0.059021,1723.0,15643.0,12153.0,NaN,NaN,NaN
328,VW,Resultats_VW,GROUP,2017,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13818.0,0.060196,-146.0,13673.0,11463.0,NaN,NaN,NaN
329,VW,Resultats_VW,GROUP,2016,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7103.0,0.032692,189.0,7292.0,5379.0,NaN,NaN,NaN

In [14]:
df['Flux de trésorerie entrants/sortants liés aux activités opérationnelles']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
325   NaN
326   NaN
327   NaN
328   NaN
329   NaN
Name: Flux de trésorerie entrants/sortants liés aux activités opérationnelles, Length: 72, dtype: float64

In [4]:
df1 = df[df['Nom_fichier']=='Actifs_BMW']
display(df1)
df2 = df[df['Nom_fichier']=='cashflow_BMW']
display(df2)

,Entreprise,Nom_fichier,Type,Annee,Immobilisations incorporelles,Immobilisations corporelles,Produits loués,Participations comptabilisées,Autres investissements,Créances de financement des ventes,...,modele,unites_vendues,Résultats opérationnels,Marge brute,Résultat financier,Bénéfices avant impôt,Bénéfice net de l'année,vente,Continents,Pays
0,BMW,Actifs_BMW,GROUP,2021,12980.0,22390.0,44700.0,5112.0,1241.0,51712.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW,Actifs_BMW,GROUP,2020,12342.0,21850.0,41995.0,3585.0,735.0,48025.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMW,Actifs_BMW,GROUP,2019,11729.0,23245.0,42609.0,3199.0,703.0,51030.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BMW,Actifs_BMW,GROUP,2018,10971.0,19801.0,38572.0,2624.0,739.0,48109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BMW,Actifs_BMW,GROUP,2017,9464.0,18471.0,36257.0,2769.0,690.0,48321.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,BMW,Actifs_BMW,GROUP,2016,8157.0,17960.0,37789.0,2546.0,560.0,48032.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Entreprise,Nom_fichier,Type,Annee,Immobilisations incorporelles,Immobilisations corporelles,Produits loués,Participations comptabilisées,Autres investissements,Créances de financement des ventes,...,modele,unites_vendues,Résultats opérationnels,Marge brute,Résultat financier,Bénéfices avant impôt,Bénéfice net de l'année,vente,Continents,Pays
35,BMW,cashflow_BMW,GROUP,2021,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,BMW,cashflow_BMW,GROUP,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,BMW,cashflow_BMW,GROUP,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,BMW,cashflow_BMW,GROUP,2018,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,BMW,cashflow_BMW,GROUP,2017,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,BMW,cashflow_BMW,GROUP,2016,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df1['Total des actifs']

0    229527.0
1    216658.0
2    228034.0
3    208980.0
4    195506.0
5    188535.0
Name: Total des actifs, dtype: float64

In [8]:
df1['Flux de trésorerie entrants/sortants liés aux activités opérationnelles']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: Flux de trésorerie entrants/sortants liés aux activités opérationnelles, dtype: float64

In [9]:
df2['Flux de trésorerie entrants/sortants liés aux activités opérationnelles']

35    15903.0
36    13251.0
37     3662.0
38     5051.0
39     5909.0
40     3173.0
Name: Flux de trésorerie entrants/sortants liés aux activités opérationnelles, dtype: float64

In [11]:
df_final.loc[df1.index,'Flux de trésorerie entrants/sortants liés aux activités opérationnelles']=df_final.iloc[df2.index]['Flux de trésorerie entrants/sortants liés aux activités opérationnelles'].values

In [13]:
df_final['Flux de trésorerie entrants/sortants liés aux activités opérationnelles']

0      15903.0
1      13251.0
2       3662.0
3       5051.0
4       5909.0
        ...
577        NaN
578        NaN
579        NaN
580        NaN
581        NaN
Name: Flux de trésorerie entrants/sortants liés aux activités opérationnelles, Length: 582, dtype: float64

In [15]:
df_final.to_csv('donnees_combinees.csv',index=False)